############################## navigation ###############################
# main menu
#[[main]]
#name = "Faq"
#url = "faq"
#weight = 1
## footer menu
#[[footer]]
#name = "Changelog"
#url = "changelog"
#weight = 1
#[[footer]]
#name = "Contact"
#url = "contact"
#weight = 2
#[[footer]]
#name = "FAQ"
#url = "faq"
#weight = 3
