logo = "images/logo.png"
description = "This is meta description"
google_analitycs_id = "UA-146893148-1"

[[social]]
title = "twitter"
icon = "ti-twitter-alt"
link = ""

[[social]]
title = "github"
icon = "ti-github"
link = "https://github.com/dnb-hugo/hugonewsletter.com/"
