############################# Plugins ##############################
# CSS Plugins
[[plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[plugins.css]]
link = "plugins/search/auto-complete.css"
[[plugins.css]]
link = "plugins/featherlight/featherlight.min.css"
# JS Plugins
[[plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[plugins.js]]
link = "plugins/masonry/masonry.min.js"
[[plugins.js]]
link = "plugins/featherlight/featherlight.min.js"
[[plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
[[plugins.js]]
link = "plugins/search/auto-complete.js"
[[plugins.js]]
link = "plugins/search/search.js"
[[plugins.js]]
link = "plugins/search/lunr.min.js"

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "Patrick Kollitsch"
# contact form action
contact_form_action = "https://formspree.io/f/xbjpaonv" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-146893148-1"

# Preloader
[preloader]
enable = true
preloader = "images/logo.png" # use jpg, png, svg or gif format.

# Navigation button bordered
[navigation_button_bordered]
enable = false
label = "Changelog"
link = "changelog"

# Navigation button solid
[navigation_button_solid]
enable = true
label = "Contact"
link = "/contact"

############################# social site ########################
[[social]]
title = "twitter"
icon = "ti-twitter-alt"
link = "https://twitter.com/hugonewsletter"

[[social]]
title = "github"
icon = "ti-github"
link = "https://github.com/dnb-hugo/hugonewsletter.com/"
